[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT:-8000}'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 