[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app" 